# -*- coding: utf-8 -*-
"""WebScraping PokemonDB pokedex

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaV1SZ_yCeDY46i6pdlfkrbN1r0Hn9Yc
"""

import requests
from bs4 import BeautifulSoup

url = 'https://pokemondb.net/pokedex/national'
resposta = requests.get(url)
html = resposta.text

"""# Coleta dos dados dos pokemons"""

soup = BeautifulSoup(html, 'html.parser')
secoes = soup.find_all('div', class_ = 'infocard-list')

for secao in secoes:
  pokemons = secao.find_all('div', class_ = 'infocard')

  geracao_lista = secao.find_previous_sibling('h2').text.split().pop(1)
  geracao = int(geracao_lista)
  for pokemon in pokemons:
    # Nome do pokemon
    nome = pokemon.find('a', class_ = 'ent-name').text

    # Link da imagem do pokemon
    imagem = pokemon.find('img', class_ = 'img-fixed img-sprite')['src']

    # Número da pokedex
    n_pokedex = pokemon.find('small').text

    # Tipagem do pokemon
    tipos_tag = pokemon.find('span', class_ = 'infocard-lg-data text-muted')
    tipos_lista = [
        tipo.text for tipo in tipos_tag.find_all('a')
        if '/type/' in tipo.get('href')
        ]
    tipos = ', '.join(tipos_lista)

    # Link de cada pokemon
    a_tag = pokemon.find('span', class_ = 'infocard-lg-img').find('a')
    link_pokemon = 'https://pokemondb.net' + a_tag['href']

    resposta_pokemon = requests.get(link_pokemon)
    html_poke = resposta_pokemon.text
    soup_pokemon = BeautifulSoup(html_poke, 'html.parser')

    div_tabela = soup_pokemon.find('div', class_ = 'resp-scroll')
    tabela = div_tabela.find('table', class_ = 'vitals-table')
    fatia = tabela.find('tbody')
    atributos = fatia.find_all('tr')
    for atributo in atributos:
      muleta_valor_atributo = atributo.find('th')
      valor_atributo_str = muleta_valor_atributo.find_next_sibling().text
      nome_atributo = atributo.find('th').text
      valor_atributo = int(valor_atributo_str)

      if nome_atributo == 'HP':
        hp = valor_atributo
      elif nome_atributo == 'Attack':
        atk = valor_atributo
      elif nome_atributo == 'Defense':
        defense = valor_atributo
      elif nome_atributo == 'Sp. Atk':
        sp_atk = valor_atributo
      elif nome_atributo == 'Sp. Def':
        sp_def = valor_atributo
      elif nome_atributo == 'Speed':
        speed = valor_atributo

    total = (hp + atk + defense + sp_atk + sp_def + speed)

    print(f'Nome: {nome}')
    print(f'Link da imagem: {imagem}')
    print(f'Número da pokedéx: {n_pokedex}')
    print(f'Tipagem: {tipos}')
    print(f'Geração: {geracao}')
    print(f'HP: {hp}')
    print(f'Atk: {atk}')
    print(f'Def: {defense}')
    print(f'Sp atk: {sp_atk}')
    print(f'Sp def: {sp_def}')
    print(f'Speed: {speed}')
    print(f'Total: {total}')
    print(100*'-')

"""# Criação de uma lista com valores separados por vírgula"""

lista_pokemons = []

soup = BeautifulSoup(html, 'html.parser')
secoes = soup.find_all('div', class_ = 'infocard-list')

for secao in secoes:
  pokemons = secao.find_all('div', class_ = 'infocard')

  geracao_lista = secao.find_previous_sibling('h2').text.split().pop(1)
  geracao = int(geracao_lista)
  for pokemon in pokemons:
    # Nome do pokemon
    nome = pokemon.find('a', class_ = 'ent-name').text

    # Link da imagem do pokemon
    imagem = pokemon.find('img', class_ = 'img-fixed img-sprite')['src']

    # Número da pokedex
    n_pokedex = pokemon.find('small').text

    # Tipagem do pokemon
    tipos_tag = pokemon.find('span', class_ = 'infocard-lg-data text-muted')
    tipos_lista = [
        tipo.text for tipo in tipos_tag.find_all('a')
        if '/type/' in tipo.get('href')
        ]
    tipos = ', '.join(tipos_lista)

    # Link de cada pokemon
    a_tag = pokemon.find('span', class_ = 'infocard-lg-img').find('a')
    link_pokemon = 'https://pokemondb.net' + a_tag['href']

    resposta_pokemon = requests.get(link_pokemon)
    html_poke = resposta_pokemon.text
    soup_pokemon = BeautifulSoup(html_poke, 'html.parser')

    div_tabela = soup_pokemon.find('div', class_ = 'resp-scroll')
    tabela = div_tabela.find('table', class_ = 'vitals-table')
    fatia = tabela.find('tbody')
    atributos = fatia.find_all('tr')
    for atributo in atributos:
      muleta_valor_atributo = atributo.find('th')
      valor_atributo_str = muleta_valor_atributo.find_next_sibling().text
      nome_atributo = atributo.find('th').text
      valor_atributo = int(valor_atributo_str)

      if nome_atributo == 'HP':
        hp = valor_atributo
      elif nome_atributo == 'Attack':
        atk = valor_atributo
      elif nome_atributo == 'Defense':
        defense = valor_atributo
      elif nome_atributo == 'Sp. Atk':
        sp_atk = valor_atributo
      elif nome_atributo == 'Sp. Def':
        sp_def = valor_atributo
      elif nome_atributo == 'Speed':
        speed = valor_atributo

    total = (hp + atk + defense + sp_atk + sp_def + speed)

    lista_pokemons.append({
        'nome_pokemon': nome, 'num_pokedex': n_pokedex,
        'tipos': tipos, 'HP': hp,
        'atk': atk, 'Def': defense,
        'sp_atk': sp_atk, 'sp_def': sp_def,
        'Speed': speed, 'total': total
    })

for item in lista_pokemons:
  print(item)

import pandas as pd

df = pd.DataFrame(lista_pokemons)
df

df.to_csv('pokedex_inteira.csv')